### ISSUE TITLE
Doesn't support receiving binary mqtt messages

### ISSUE THREAD

**Issue by bettse** [VictorHAS/mqtt-react-hooks#10]
I'm working with a device that uses binary messages and publishing isn't a problem using `Uint8Array`, but after subscribing to a topic I never got any `msgs`.  I'm seeing the messages in websocket communication in the browser's developer tools, so I suspect it is a result of the `toString()`.

I just wanted to make an issue to note the limitation in case it is something others run into.  I appreciate the effort put into the library and respect that this may not get fixed.

**Comment by VictorHAS** [comment]
Sorry for the delay, but just now I had time to fix all the problems and improve it. I released a version 2.0.0 and that could solve your problem

you can now use a parserMethod option passing in the Connector, so you will return the message in Buffer Format
