### ISSUE TITLE
Attempted import error: 'uuid' does not contain a default export (imported as 'i').

### ISSUE THREAD

**Issue by zhenghaohe** [VictorHAS/mqtt-react-hooks#12]
Got this error after installing the package to a TypeScript React project
```
Failed to compile.

./node_modules/mqtt-react-hooks/dist/index.es.js
Attempted import error: 'uuid' does not contain a default export (imported as 'i').

```
The version is `"mqtt-react-hooks": "^1.2.0"`

**Comment by krzysztof-miemiec** [comment]
I guess there is a mismatch between `uuid` installed in your project and expectations of `mqtt-react-hooks` package. Looking at it's peer dependencies, you should manually add packages that match those versions:
```json
{
    "react": ">= 16.8.0",
    "react-dom": ">= 16.8.0",
    "uuid": "^3.4.0",
    "yup": ">= 0.27.0"
}
```
So, any react above 16.8 and yup above 0.27 are ok, but uuid has to stay **below 4**.

@VictorHAS: is there any reason why `mqtt-react-hooks` specifies `uuid` in `peerDependencies`? How about an upgrade to 8.x and making it a dependency?

**Comment by hyh123a** [comment]
Yes, it works well. 
This problem may happen if you use "npm" tools. It will not install the peer dependencies. 
Instead, 'yarn' tool is always ok.

**Comment by VictorHAS** [comment]
Now the types are returning correctly and I'm not using UUID, as I no longer export a series of messages
