### ISSUE TITLE
Unable to connect to test brokers using certain URLs

### ISSUE THREAD

**Issue by thomaspaulin** [VictorHAS/mqtt-react-hooks#15]
I'm unable to connect to the Mosquitto test broker via the URL listed in the README (`mqtt://test.mosquitto.org:1884`). I have also tried:
- `mqtt://test.mosquitto.org:8883` - Fail
- `mqtt://test.mosquitto.org:1883/` - Fail
- `ws://test.mosquitto.org:8080/` - Fail
- `wss://test.mosquitto.org:8081/` - Connects

So far only the last URL connects. I suspect those using the MQTT protocol fail because [MQTT.js can't open the TCP socket by default](https://github.com/mqttjs/MQTT.js/issues/628#issuecomment-341675286).

EDIT: The error I see is `WebSocket connection to 'ws://test.mosquitto.org:1884/' failed`

**Comment by VictorHAS** [comment]
In the browser you will only be able to use 'mqtts' or wss protocol since it's websocket only, it was a mistake of mine to have put as 'mqtt://' 

In node you will be able to connect normally using mqtt an using port 1883

**Comment by thomaspaulin** [comment]
Thanks for the reply! I primarily created this issue for those Googling for solutions :)
