### ISSUE TITLE
Export types for Typescript

### ISSUE THREAD

**Issue by Thunderkill** [VictorHAS/mqtt-react-hooks#3]
There are no types being exported for typescript users.

**Comment by Thunderkill** [comment]
My temporary solution is to create a module declaration you can use here. Not sure if it contains all the needed types but fits for my use.

mqtt-react-hooks.d.ts
```
declare module "mqtt-react-hooks" {
  import { MqttClient, IClientOptions } from "mqtt";
  export interface MqttContext<T> {
    status: string;
    mqtt: MqttClient | undefined;
    messages: Message<T>[];
    lastMessage: Message<T> | undefined;
    addMessage: (message: Message<T>) => void;
  }

  export interface MessageStructure {
    [key: string]: string;
  }

  export interface Message<T> {
    topic: string;
    message?: T | MessageStructure;
    id: string;
  }

  interface ConnectorProps {
    brokerUrl?: string | object;
    opts?: IClientOptions | undefined;
    children: React.ReactNode;
  }

  export function Connector(props: ConnectorProps): JSX.Element;

  export function useSubscription<T>(
    topic: string
  ): {
    msgs: Message<T>[];
    mqtt: MqttClient | undefined;
    status: string;
    lastMessage: Message<T> | undefined;
    lastMessageOnTopic: Message<T>;
    topic: string;
  };

  export function useMqttState<T>(): {
    status: string;
    mqtt: MqttClient | undefined;
    allMessages: Message<T>[];
    lastMessage: Message<T> | undefined;
  };
}

```

**Comment by alexgorbatchev** [comment]
Typings are now included in package.json, however the actual type definition file is absent from the dist folder in v1.2.0

**Comment by VictorHAS** [comment]
Hey @alexgorbatchev , I'm working on a new version with types and tests. I'm having some problems with @testing-library/react-hooks showing warnings that I don't know how to fix it, but nothing critical (act warnings). That’s why I haven’t released a new version yet, the changes are in the development branch

**Comment by alexgorbatchev** [comment]
I tried the `develop` branch and all tests are passing for me without warnings. Is that the right branch?

**Comment by VictorHAS** [comment]
Yes, this warning: 

` console.error
      Warning: An update to Connector inside a test was not wrapped in act(...).
      
      When testing, code that causes React state updates should be wrapped into act(...):
      
      act(() => {
        /* fire events that update state */
      });
      /* assert on the output */
      
      This ensures that you're testing the behavior the user would see in the browser. Learn more at https://fb.me/react-wrap-tests-with-act
          in Connector (created by wrapper)
          in wrapper

      24 |     mqttInstance.on('connect', () => setStatus('connected'));
      25 |     mqttInstance.on('reconnect', () => setStatus('reconnecting'));
    > 26 |     mqttInstance.on('close', () => setStatus('closed'));
         |                                    ^
      27 |     mqttInstance.on('error', error => setStatus(error.message));
      28 | 
      29 |     return () => {
`
