### ISSUE TITLE
Messages are never cleared

### ISSUE THREAD

**Issue by Thunderkill** [VictorHAS/mqtt-react-hooks#4]
The message array (msgs) in useSubscription(topic) always returns all messages detected and are never cleared. This is effectively a memory leak since all messages are stored in that said array, imagine a IOT device pushing millions of messages to a topic and this array contains them all.

I feel that the message array should only contain the retained messages of the topic, also i feel like useSubscription should return a subscription function we could use to subscribe to new messages. Example:

```
const { subscribe, unsubscribe } = useSubscription("test");

useEffect(() => {
    const id = subscribe(message => {
        console.log(message);
    });

    return function cleanup() {
        unsubscribe(id);
    }
}, []);
```

OR 

```
const { subscribe } = useSubscription("test");

useEffect(() => {
    const unsubscribe = subscribe(message => {
        console.log(message);
    });

    return function cleanup() {
        unsubscribe();
    }
}, []);
```

**Comment by VictorHAS** [comment]
Hi @Thunderkill , thanks for the feedback! I will be giving a reformulated in both useSubscription and types as requested in issues #3 . Anything can send a pull request and I will do the analysis.
