### ISSUE TITLE
Authentication?

### ISSUE THREAD

**Issue by Stephan-MDD** [VictorHAS/mqtt-react-hooks#9]
Hi, im using a MQTT broker with authentication but cant figure out where to parse the credentials in this library.
Am I blind or is it not implemented yet? :)

_thanks in advance_

**Comment by VictorHAS** [comment]
Hi Stephan, Yes you can put the credentials on Connector wrapper using prop `opts = { {/* All options you need from Mqtt.js*/ } } `

https://github.com/mqttjs/MQTT.js/blob/master/README.md#connect

All options from connect are supported.

**Comment by Stephan-MDD** [comment]
Thanks :) - Im getting a new error after implementing the `opts`.

**Comment by VictorHAS** [comment]
@Stephan-MDD  Basically it is a protocol error as has already been said. Have you configured Broker to listen to websockets on a different port? example 1884

`/etc/mosquitto/mosquitto.conf`

listener 1884
protocol websockets

**Comment by Stephan-MDD** [comment]
I have a simple custom conf file which contains the `listener` and `protocol` :)

```bash
allow_anonymous false
password_file /usr/local/Cellar/mosquitto/1.6.10/etc/mosquitto/passwd.txt

listener 9001
protocol websockets
```

**Comment by VictorHAS** [comment]
In the brokerUrl on Connector wrapper, how are you passing the url? `brokerUrl="protocol://ip:9001` ?

**Comment by Stephan-MDD** [comment]
Yes, i tried that too but it still gives me errors.
I made a simple component where I try to connect to mosquittos test broker, but it gives me errors too :(  
reference: https://test.mosquitto.org/ws.html

_Thanks for helping me Victor, if you want me to make a new issue so this can be closed you just tell me :D_ 

**React Component**
```js
import React from 'react';
import { Connector, useMqttState } from 'mqtt-react-hooks';

const App = () => {
  const { mqtt } = useMqttState();
  const handleClick = () => mqtt.publish('test', 'Hello from Client!');

  return (
    <Connector brokerUrl="ws://test.mosquitto.org/mqtt" opts={{ password: 'pass', username: 'client', topic: 'mdd' }}>
      <input type="button" value="emit" onClick={handleClick} />
    </Connector>
  );
};

export default App;
```

**Error Message**
```bash
WebSocket connection to 'ws://test.mosquitto.org/mqtt' failed: Error during WebSocket handshake: Unexpected response code: 301
```

**Comment by VictorHAS** [comment]
@Stephan-MDD seeing the error, code 301 is when a URL is moved permanently. I did the test now connecting via wss (mqtts) to my server passing password and user and it worked fine. The library is working smoothly, just need to make adjustments to the server to accept connections

```js
import React from 'react';
import { Connector, useMqttState } from 'mqtt-react-hooks';

const Children = () => {
  const { status } = useMqttState();

  return <span>{status}</span>;
};

const App = () => {
  return (
    <Connector
      brokerUrl="mqtts://domain:8083" // 8083
      opts={{
        password: 'pass',
        username: 'user',
      }}
    >
      <Children />
    </Connector>
  );
};

export default App;

```

**Comment by mitul-srashtasoft** [comment]
still not working

**Comment by VictorHAS** [comment]
> still not working

hey mitul, there is a new version available with types exported, can you try it again?

i'll be closing this issue, if you still having problem please open another one
